DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS request;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS request
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255) NOT NULL,
    created TIMESTAMP,
    requester BIGINT CONSTRAINT request_users_id_fk REFERENCES users (id),
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    available BOOLEAN,
    owner BIGINT CONSTRAINT items_users_id_fk REFERENCES users (id),
    request BIGINT CONSTRAINT request_users_id_fk REFERENCES request (id),
    CONSTRAINT pk_items PRIMARY KEY (id)
);
