DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255) NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE,
    requester_id BIGINT CONSTRAINT request_users_id_fk REFERENCES users (id),
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    is_available BOOLEAN,
    owner_id BIGINT CONSTRAINT items_users_id_fk REFERENCES users (id),
    request_id BIGINT CONSTRAINT items_request_id_fk REFERENCES requests (id),
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE,
    end_time TIMESTAMP WITHOUT TIME ZONE,
    item_id BIGINT CONSTRAINT bookings_items_id_fk REFERENCES items (id),
    booker_id BIGINT CONSTRAINT bookings_users_id_fk REFERENCES users (id),
    status VARCHAR(10) NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT status_values CHECK (status IN ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED'))
);

CREATE TABLE IF NOT EXISTS comments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR(255),
    item_id BIGINT CONSTRAINT comments_items_id_fk REFERENCES items (id),
    author_id BIGINT CONSTRAINT comments_users_id_fk REFERENCES users (id),
    CONSTRAINT pk_comment PRIMARY KEY (id)
);
